global:
  scrape_interval: 5s
  external_labels:
    monitor: 'monitor'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s 
    static_configs: 
      - targets: ['prometheus:9090'] ## IP Address of the localhost
  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100'] ## IP Address of the localhos
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']